### ISSUE TITLE
Performance issues in large files

### ISSUE THREAD

**Issue by sigmanor** [VPKSoft/VPKSoft.ScintillaUrlDetect#1]
Hi. Seems to need fix performance issues in large files. When I try load large files, UI is freezing.

<details>
  <summary>Video</summary>

![](https://i.imgur.com/70y7iFW.gif)
  
</details>

<details>
  <summary>And here is video with disabled UrlDetect</summary>

![](https://i.imgur.com/qp7YZCZ.gif)
  
</details>

**Comment by sigmanor** [comment]
Seems this code must help, but it doesn't.

```csharp
private void mnuThreadingEnabled_CheckedChanged(object sender, EventArgs e)
        {
            try
            {
                var menuItem = (ToolStripMenuItem) sender;
                ScintillaUrlDetect.UseThreadsOnUrlStyling = menuItem.Checked;
            }
            catch (Exception ex)
            {
                MessageBox.Show($@"An exception occurred: '{ex.Message}'.",
                    @"Error", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1);
            }
        }
```

**Comment by VPKSoft** [comment]
Hi,
How large files are you talking about - the test application reads the entire file into memory so there is no stream seeking, etc, used to handle large files. The thread which does the URL matching launches only if the text is changed and by default after half a second of idle time. I will definitely look in to this matter within the next week. Thanks for reporting this issue 👍
There might be some condition in the library which launches the check thread without the text being changed 🙄 - meanwhile does disabling the UseThreadsOnUrlStyling property affect the efficiency - if so; that would indicate an invalid launch condition for the thread.

**Comment by VPKSoft** [comment]
Sorry, I didn't look at the other video, I now have software wrapping in a Not Responding state of 35 megabytes of text containing "test" into a multi-lined file...

**Comment by VPKSoft** [comment]
It definitely takes a huge amount of CPU and memory, but the thread launch for the URL check seems to do the checking only when the text is changed within the Scintilla control:
![image](https://user-images.githubusercontent.com/40712699/68090112-bbb14b80-fe78-11e9-9c66-d4c91a6df2a2.png)

Resizing, selecting, etc doesn't seem to launch the thread..
![image](https://user-images.githubusercontent.com/40712699/68090164-409c6500-fe79-11e9-8023-67398c0029ae.png)

**Comment by sigmanor** [comment]
@VPKSoft I'm trying to load this file, it's only 9,75 mb size.
[extra large.txt](https://github.com/VPKSoft/VPKSoft.ScintillaUrlDetect/files/3801959/extra.large.txt)

I thought that the problem was only in my project, so I specifically downloaded your test project. And when I'm deleting this line `urlDetect = new ScintillaUrlDetect(scintillaTest);` file starts loading very fast. You can see it in the second video.

**Comment by sigmanor** [comment]
@VPKSoft Yes, its dont freezing on resizing, selecting, etc. Its freezing when i load file (even without any links) and when im pasting links to editor.
Look at this video for example:
![](https://i.imgur.com/mZy3KNG.gif)
- Open context menu (UI is freezing)
- Press PASTE item (UI is freezing)

**Comment by VPKSoft** [comment]
Okay, there is a memory leak somewhere - seems to be piling up every time you change the text... I'll look into that then, I got to about 4 gigabytes before shutting the the debug session. So at least I know where to look this bug from 🙂

**Comment by sigmanor** [comment]
@VPKSoft Okay. Thank you for responding.

**Comment by VPKSoft** [comment]
Hi, seems there is no memory leak after all - I must unify the regular expressions used by the software to improve the performance.

**Comment by VPKSoft** [comment]
Hi, I managed to optimize the memory consumption from peak 4GB to peak 1GB and the speed of validating a file of 33 082 605 bytes containing the word text from 12.3383 to 9.8696 seconds average (100 iterations). The second step is to validate only the visible text area which might take some time. I'll let you know when it's done. I'm going to release an updated NuGet before that because the library works fine with my text editors, but I ow you a huge thanks 😃 The next thing to do is to view this article: https://github.com/jacobslusser/ScintillaNET/issues/141 and learn about the visible text area 🤔

**Comment by sigmanor** [comment]
@VPKSoft Thank you very much 😊
