### ISSUE TITLE
Only validate the visible area

### ISSUE THREAD

**Issue by VPKSoft** [VPKSoft/VPKSoft.ScintillaUrlDetect#2]
To speed up the URL validation only validate the visible are of the [ScintillaNET](https://github.com/jacobslusser/ScintillaNET). Thanks to @Sigmanor for pointing out the performance issue with large files 👍

**Comment by VPKSoft** [comment]
Hi. I updated the [NuGet](https://www.nuget.org/packages/VPKSoft.ScintillaUrlDetect/1.0.0.3) and the repository to only mark URLs on the visible contents of the control. TODO: Next do the same to the [VPKSoft.ScintillaSpellCheck](https://github.com/VPKSoft/VPKSoft.ScintillaSpellCheck).

![2019-11-06_19-50-15](https://user-images.githubusercontent.com/40712699/68327351-db917b00-00d5-11ea-8546-a8010ac0c6f4.gif)

I'll leave this open for a few weeks for improvement suggestions and/or bug reports...

**Comment by VPKSoft** [comment]
At least the update seems to be working fine with one of my project:
![image](https://user-images.githubusercontent.com/40712699/68329012-0e893e00-00d9-11ea-9ca3-d588cf29c147.png)

**Comment by sigmanor** [comment]
@VPKSoft Seems now it work fast, I will test it more closely later. Thank you ☺️

**Comment by sigmanor** [comment]
@VPKSoft I tested it in more detailed, and seems everything is working fine now, thanks again.

**Comment by VPKSoft** [comment]
Closing as resolved.
