### ISSUE TITLE
Weird cursor behavior

### ISSUE THREAD

**Issue by sigmanor** [VPKSoft/VPKSoft.ScintillaUrlDetect#3]
Hello. I found a weird issue. I already seen such cursor behavior in the default **richtextbox** control, but I fixed it by updating **.Net Framework** version to **4.7.2** This not a critical bug, but very nasty, as for me. So, what the point: when I paste a link, and there is no new line after the link, cursor remain **Hand** icon, throughout all area of the editor. After I press **Enter**, and paste new line, cursor becomes regular for editor: **IBeam**.

Seems this is bug of **ScintillaNet**, but I thought, maybe it can be fixed in **VPKSoft.ScintillaUrlDetect**? Because exactly your project add to **ScintillaNet** easy url highlight support.

Here is the video:
![](https://i.imgur.com/Xp1IE0f.gif)

Thank you.

**Comment by VPKSoft** [comment]
Hi,
Yes, this seems to be a known issue with the [ScintillaNET](https://github.com/jacobslusser/ScintillaNET) and is reported in the issue [111](https://github.com/jacobslusser/ScintillaNET/issues/111#issuecomment-136045423). There is still an [issue](https://github.com/jacobslusser/ScintillaNET/issues/182) open to fix this, but no one has yet responded with a valid solution. I'll have to take a look for the code behind the `Scintilla.CharPositionFromPoint(point.X, point.Y);` to see if I'm going to be able to fix this.
```cs
        // handle the cursor set in case the mouse is on an URL..
        private void Scintilla_MouseMove(object sender, MouseEventArgs e)
        {
            var point = e.Location;

            // get the character index at the click location..
            int charPosition = scintilla.CharPositionFromPoint(point.X, point.Y);
```
However I'm not going to touch the [ScintillaNET](https://github.com/jacobslusser/ScintillaNET)'s code and moreover not going to touch the C++ code with the [Scintilla](https://www.scintilla.org). Lets hope I'll find an easy solution to this 🤔

Ps. Also thinking of adding [ellipsis](https://social.msdn.microsoft.com/Forums/vstudio/en-US/676519cd-4cb4-43cb-8a4d-b67e28e0f73d/how-to-get-ellipsis-in-the-middle-of-the-text?forum=winappswithcsharp) possibility to the URL tool tip as some URLs tend to be quite long.

**Comment by sigmanor** [comment]
@VPKSoft As for me, better to make able to open links by the left mouse click (Later I will look in to your source code, to understand how to do this.) 

About the tooltips, I prefer disable them at all.

**Comment by VPKSoft** [comment]
Hi, I found a solution; the call to the `Scintilla.CharPositionFromPoint(point.X, point.Y);` must be replaced with `Scintilla.CharPositionFromPointClose(point.X, point.Y);`...
I'll probably release a fix to this this evening then 🙄

**Comment by sigmanor** [comment]
That awesome! Thanks 😊

**Comment by VPKSoft** [comment]
There you go:
![image](https://user-images.githubusercontent.com/40712699/68420217-8bcdb500-01a4-11ea-9b85-bad0285e053d.png)

The NuGet should be available soon:
![image](https://user-images.githubusercontent.com/40712699/68420342-d18a7d80-01a4-11ea-9105-7ab6c22a8d3e.png)


Now to report the solution the [ScintillaNET](https://github.com/jacobslusser/ScintillaNET) ... 😊

**Comment by VPKSoft** [comment]
There you go:
![image](https://user-images.githubusercontent.com/40712699/68420217-8bcdb500-01a4-11ea-9b85-bad0285e053d.png)

The NuGet should be available soon:
![image](https://user-images.githubusercontent.com/40712699/68421033-2f6b9500-01a6-11ea-9bea-7f7a987bc51a.png)


Now to report the solution the [ScintillaNET](https://github.com/jacobslusser/ScintillaNET) ... 😊

**Comment by sigmanor** [comment]
Yes, I already updated, perfect. I think the issue can be closed?

**Comment by sigmanor** [comment]
One more thing, if you hold CTRL and click in any area in the left or in the down, link will be open. I'm telling about situation when before the link is no new line. I think this must be fixed.

**Comment by VPKSoft** [comment]
You can disable the behaviour by setting the `UseDwellToolTip` property to false and set the `AllowProcessStartOnUrlClick` to false. I'll have to go to bed now as its UTC+2 and I have a workday tomorrow 😴 Everything is documented in the XML-file though 😎 And yes, if the link opens by clicking the wrong location it indeed must be fixed...

**Comment by VPKSoft** [comment]
Fixed - you are a very good software tester 😀

**Comment by sigmanor** [comment]
It's because your projects is quite interesting, as for me. 

Sorry if I bothering you :sweat_smile:

**Comment by VPKSoft** [comment]
No bother at all - it's good to have a less buggy piece software 👍
Weird though that a method called `CharPositionFromPoint(point.X, point.Y);` is less exact than `CharPositionFromPointClose(point.X, point.Y);` I did thought otherwise 🙄
Closing as resolved.
